languageCode = "en-us"
title = "Paul Daniel Iway"
theme = "hugo-paper"
publishDir = "docs"

[[menu.main]]
  identifier = "articles"
  name = "Articles"
  title = "Articles"
  url = "/articles/"
  weight = 10